Develop
stefan-marinkov-ey/NASA pull request #1
Opened 2021-06-23 20:10 UTC by stefan-marinkov-ey

Landing Page - Carousel, 2 Static Pages, Icon = HomePage.
Carousel - Back-Next Buttons, Indicators, Indicators onClick.

2021-06-25 15:15 UTC, mitrovic-jovana commented on nasa-project/src/App.js
>  import Terms from './pages/Terms'
Be consistent with how you end your code. Either use ; always or don't use it at all. I would say most common practice is to use it.
Also, try to be consistent with the way you organize your imports. Some of the best practices is to follow this order:

Built-in imports

External imports

Internal imports

2021-06-25 15:15 UTC, mitrovic-jovana commented on nasa-project/src/App.js
>    const url = `https://api.nasa.gov/planetary/apod?api_key=lb0B64hhGmjsIqCdhwHkErxN3gJGZcfRNbRxJIHb&count=${numberOfCards}`
Think about storing urls and api keys in separate files. That way if they are changed in some point of time in the future you need to change it only in one place. Also, if some url or api key is used in multiple components, it would be could to store them in some centralized place

2021-06-25 15:15 UTC, mitrovic-jovana commented on nasa-project/src/App.js
> +    <div className="wrapperApp">
Try formatting jsx properly. Here for example child elements should be indented.

2021-06-25 15:15 UTC, mitrovic-jovana commented on nasa-project/src/components/CardHolder/CardHolder.jsx
> +const CardHolder = ({apod}) => {
This is a good place to use implicit return in arrow functions

2021-06-25 15:15 UTC, mitrovic-jovana commented on nasa-project/src/components/CardHolder/index.js
> +import CardHolder from "./CardHolder";
Is there any particular reason why every component has this index.js file for export?

2021-06-25 15:15 UTC, mitrovic-jovana commented on nasa-project/src/components/Carousel/Carousel.jsx
>  const Carousel = ({numberOfCards}) => {
Missing spaces

2021-06-25 15:21 UTC, mitrovic-jovana commented on nasa-project/src/components/Carousel/Carousel.jsx
>  import useWindowSize from '../WindowSize'
I see you have two custom hooks in the app. Maybe you can make some separate folder for custom hooks and they could have the same naming structure

2021-06-25 15:28 UTC, mitrovic-jovana commented on nasa-project/src/components/Carousel/Carousel.jsx
> +    }, [width])
You are missing "spanMaker" in the dependency array here

2021-06-25 16:00 UTC, mitrovic-jovana requested changes
Hi Stefan, good work! Application looks good, carousel and pagination work as expected, great job on that. Big plus on using Context, keep it up! I would just move context outside components folder. It’s good to separate bigger sections so the navigation through project structure is easier.

I left you a few suggestions in the comments, but the thing that needs to be updated is formatting. On lot of places, formatting is not good and it’s not consistent. I would suggest you use extensions for formatting (ESLint or Prittier) and change settings in VS code to auto format on save. There is no need to manually format everything. Properly formatted code is a must

2021-06-28 09:22 UTC, stefan-marinkov-ey commented on nasa-project/src/App.js
>    const url = `https://api.nasa.gov/planetary/apod?api_key=lb0B64hhGmjsIqCdhwHkErxN3gJGZcfRNbRxJIHb&count=${numberOfCards}`
Base url and api key are stored in variables.

2021-06-28 09:28 UTC, stefan-marinkov-ey commented on nasa-project/src/components/CardHolder/index.js
> +import CardHolder from "./CardHolder";
Yes. Every JSX file have extension JSX.
I exported them into index, the exported from there.
When we use them in some different components, it's cleaner when we import them.

2021-06-28 09:29 UTC, stefan-marinkov-ey commented on nasa-project/src/components/Carousel/Carousel.scss
> +            margin: .5rem .5rem;
This is just overlook

2021-06-28 09:33 UTC, stefan-marinkov-ey commented on nasa-project/src/components/Carousel/Carousel.jsx
>  const Carousel = ({numberOfCards}) => {
ES Lint installed

2021-06-28 13:36 UTC, stefan-marinkov-ey commented on nasa-project/src/components/Carousel/Carousel.jsx
> +    }, [width])
done

2021-06-28 13:46 UTC, stefan-marinkov-ey commented on nasa-project/src/components/CardHolder/CardHolder.jsx
> +const CardHolder = ({apod}) => {
done

2021-07-02 14:55 UTC, stefan-marinkov-ey commented on nasa-project/src/App.js
>  import Terms from './pages/Terms'
Done

2021-07-02 14:55 UTC, stefan-marinkov-ey commented on nasa-project/src/App.js
> +    <div className="wrapperApp">
done

2021-07-02 14:56 UTC, stefan-marinkov-ey commented on nasa-project/src/components/CardHolder/index.js
> +import CardHolder from "./CardHolder";
done

2021-07-02 15:19 UTC, mitrovic-jovana commented on nasa-project/src/components/CardHolder/CardHolder.jsx
> +      style={{ color: "black", textDecoration: "none" }}
I would recommend to add className here and move styling in css files rather than inline style. Inline styles only apply to that specific element. If you need to reproduce that same style to some other html element you would need to define it again for that element

2021-07-02 15:19 UTC, mitrovic-jovana commented on nasa-project/src/components/CardPage/CardPage.jsx
> +            <img src={cardInfo.url} />
Img tags require alt attribute

2021-07-02 15:20 UTC, mitrovic-jovana commented on nasa-project/src/components/CardPage/CardPage.jsx
> +            <h2>{cardInfo.title}</h2>
It would look nicer if you destructure cardInfo object

2021-07-02 15:22 UTC, mitrovic-jovana commented on nasa-project/src/components/CardPage/CardPage.jsx
> +          <div key={title} className="CardPage">
Be consistent with how you format classNames. Here for example "CardPage" is capitalized and on most of the places your class names start with lower case

2021-07-02 15:29 UTC, mitrovic-jovana commented on nasa-project/src/components/Carousel/Carousel.jsx
> +  }, [width, spanMaker]);
I know I mentioned before that spanMarker is missing in dependency array here and that's because I saw warning in the console. But sometimes even if you have warning, adding something in dependency array can cause an issue. Like in this case, spanMaker function makes the dependencies of useEffect hook change on every render. Please take a look at the warning in the console and be careful with adding dependencies.

2021-07-02 15:29 UTC, mitrovic-jovana commented on nasa-project/src/components/Carousel/Carousel.jsx
> +          <div className="Carousel">
Here className is also capitalized

2021-07-02 15:31 UTC, mitrovic-jovana commented on nasa-project/src/components/Carousel/Carousel.jsx
> +                let activePage =
If you are not reassigning value to the activePage variable, it's better to use const

2021-07-02 15:32 UTC, mitrovic-jovana commented on nasa-project/src/components/Carousel/Carousel.jsx
> +                    style={{ backgroundColor: "#747480" }}
Remove inline style, add classes to jsx and css files

2021-07-02 15:33 UTC, mitrovic-jovana commented on nasa-project/src/components/Carousel/Carousel.jsx
> +                  ></span>
If your html tag doesn’t have any children, use self-closing tags

2021-07-02 15:34 UTC, mitrovic-jovana commented on nasa-project/src/components/FileWithData/index.js
> +export let numberOfCards = 24;
Good job on adding separate file for constants!

2021-07-02 15:34 UTC, mitrovic-jovana commented on nasa-project/src/components/Footer/Footer.jsx
> +    <div className="Footer">
Same thing for classNames formatting

2021-07-02 15:36 UTC, mitrovic-jovana commented on nasa-project/src/components/Carousel/Carousel.jsx
> +  const desktop = width > 992;
I like that you made this variables, it improves readability. Maybe they can be stored in some separate file because there is a chance they can be used in other components as well

2021-07-02 15:39 UTC, mitrovic-jovana commented on nasa-project/src/pages/Landing/Landing.jsx
> +      {/* <div>If you want more then 16 cards - <input placeholder='enter number' onChange={ (e) => props.setNumberOfCards(e.target.value)} ></input></div> */}
If this is something that is going to be done in the future, maybe you can add some // TODO comment

2021-07-02 15:53 UTC, mitrovic-jovana requested changes
Hi Stefan, I really like how your application looks, carousel and pagination is working really great!
Kudos for improving the style of the cards, great job! 
And formatting is all good now.

I left you a few comments, there is a few things that can be improved, but they are not blockers.
However, I have to return PR just because of the 'Maximum update depth exceeded' warning in the console. I probably confused you with the first comment for spanMarker dependency missing, sorry about that. 
Whenever you change something in your dependency array, make sure nothing is broken. Sometimes even if you have a warning that some dependency is missing, think about what you want to achieve with useEffect and if you really need it in the dependency array.

2021-07-05 07:13 UTC, stefan-marinkov-ey commented on nasa-project/src/components/Carousel/Carousel.jsx
> +  const desktop = width > 992;
I have problem with scope when I do that.

2021-07-05 07:14 UTC, stefan-marinkov-ey commented on nasa-project/src/components/FileWithData/index.js
> +export let numberOfCards = 24;
Thanks

2021-07-05 07:14 UTC, stefan-marinkov-ey commented on nasa-project/src/components/Carousel/Carousel.jsx
> +                  ></span>
Done

2021-07-05 07:16 UTC, stefan-marinkov-ey commented on nasa-project/src/components/Carousel/Carousel.jsx
> +                let activePage =
Done

2021-07-05 07:16 UTC, stefan-marinkov-ey commented on nasa-project/src/components/Carousel/Carousel.jsx
> +  }, [width, spanMaker]);
Done

2021-07-05 07:21 UTC, stefan-marinkov-ey commented on nasa-project/src/components/CardPage/CardPage.jsx
> +          <div key={title} className="CardPage">
I'm consistent with formatting classNames, I used capitalized latter only when is it scss file from JSX file, like App.scss...
I learned to build fails structure on that way.
But is not a problem to go with another way without capitalized latter.

2021-07-05 07:27 UTC, stefan-marinkov-ey commented on nasa-project/src/components/CardPage/CardPage.jsx
> +            <h2>{cardInfo.title}</h2>
Done

2021-07-05 07:28 UTC, stefan-marinkov-ey commented on nasa-project/src/components/CardPage/CardPage.jsx
> +            <img src={cardInfo.url} />
Done

2021-07-05 07:29 UTC, stefan-marinkov-ey commented on nasa-project/src/components/Carousel/Carousel.jsx
> +          <div className="Carousel">
Carousel is JSX (main) file

2021-07-05 07:30 UTC, stefan-marinkov-ey commented on nasa-project/src/components/Footer/Footer.jsx
> +    <div className="Footer">
Footer is main file

2021-07-05 07:30 UTC, stefan-marinkov-ey commented on nasa-project/src/pages/Landing/Landing.jsx
> +      {/* <div>If you want more then 16 cards - <input placeholder='enter number' onChange={ (e) => props.setNumberOfCards(e.target.value)} ></input></div> */}
Done

2021-07-05 07:46 UTC, mitrovic-jovana commented on nasa-project/src/components/CardPage/CardPage.jsx
> +          <div key={title} className="CardPage">
I understand. Keep that style for formatting then 👍

2021-07-05 08:16 UTC, stefan-marinkov-ey commented on nasa-project/src/components/CardHolder/CardHolder.jsx
> +      style={{ color: "black", textDecoration: "none" }}
Done, I will pay attention about this in the future

2021-07-05 08:17 UTC, stefan-marinkov-ey commented on nasa-project/src/components/Carousel/Carousel.jsx
> +                    style={{ backgroundColor: "#747480" }}
Done

2021-07-05 10:17 UTC, mitrovic-jovana approved these changes
Great job @stefan-marinkov-ey ! Everything is working as expected, I am merging this

2021-07-05 10:18 UTC, merged